#!/bin/bash
# Every landing-page asset that is NOT screen-recorded: the four transparent
# hero sprite sheets and the CSS that drives them, plus the offline stills.
#
# This runs in the AUTHORING account, from the repo. It needs no app, no
# permissions and no capture account — only a Swift toolchain, because
# spritefilm reads the app's PNGs directly. It is deliberately not part of the
# staged capture kit.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# Named for what it holds. It used to be JUMBINI_DEMO_OUT, which is also
# capture.sh's variable for the CLIPS directory — and stage-kit.sh prints an
# instruction that exports it globally.
OUT="${JUMBINI_STILLS_OUT:-$ROOT/demo-assets/stills}"
HERO="${JUMBINI_HERO_OUT:-$ROOT/demo-assets/hero}"
# How many output pixels per pixel of source art. See the note on density in
# the generated CSS: raise this to re-render the sheets bigger, and the CSS
# follows automatically.
HERO_SCALE="${JUMBINI_HERO_SCALE:-2}"
FILM=(swift run --package-path "$HERE/spritefilm" spritefilm)

mkdir -p "$OUT" "$HERO"
cd "$ROOT"

# ---------------------------------------------------------------------------
# Hero sprite sheets, and a CSS file with the real numbers in it
#
# A sheet rather than alpha video: alpha video splits along HEVC-in-Safari
# versus VP9-in-Chrome, while a sheet is universal, a fraction of the size and
# crisp at any DPI.
#
# The facings are the ones a landing page wants: the moving poses run to the
# right, the resting poses look at the reader.
#
# The CSS is generated rather than written by hand because every number in it
# comes from the art. `spritefilm sheet` prints `frames=N cell=W height=H` on
# stdout for exactly this, and the frame rate comes from animations.json —
# the same table HeroSpecTests pins to SpriteLibrary, so the dog on the
# website cannot drift out of step with the dog in the product.
css="$HERO/hero.css"
{
  echo "/* Generated by Tools/demo/stills.sh — do not edit by hand."
  echo " * Every number here is measured from the emitted PNG or read from"
  echo " * Tools/demo/animations.json, which HeroSpecTests pins to the app."
  echo " *"
  echo " * DENSITY. These sheets are rendered at --scale $HERO_SCALE, so one"
  echo " * pixel of source art becomes ${HERO_SCALE}x${HERO_SCALE} pixels in the PNG, with"
  echo " * nearest-neighbour sampling (spritefilm sets interpolationQuality"
  echo " * .none). The declared width/height below are the PNG's OWN pixels:"
  echo " * one CSS pixel per image pixel. That is a 1x asset at this size, and"
  echo " * it is deliberate — for hand-drawn pixel art the thing that matters"
  echo " * is landing on an integer multiple of the source grid, not on the"
  echo " * device pixel ratio. A half-pixel grid is what looks wrong, and a 2x"
  echo " * asset shown at 1x CSS size resamples straight back onto one."
  echo " *"
  echo " * TO RENDER BIGGER: re-run with JUMBINI_HERO_SCALE=N. The PNGs and"
  echo " * every number in this file scale together, so nothing needs editing."
  echo " * Source frame size is always (declared width / $HERO_SCALE)."
  echo " *"
  echo " * image-rendering: pixelated keeps the edges hard if the page scales"
  echo " * these further — without it, browsers smooth the art on upscale."
  echo " */"
} >"$css"

hero_sheet() {
  local pose="$1" facing="$2"
  local file="$pose-$facing.png"
  local line frames cell height fps
  echo "hero: $pose ($facing)"
  line=$("${FILM[@]}" sheet --pose "$pose" --facing "$facing" --scale "$HERO_SCALE" --out "$HERO/$file")
  frames=${line#*frames=}; frames=${frames%% *}
  cell=${line#*cell=}; cell=${cell%% *}
  height=${line#*height=}; height=${height%% *}
  fps=$(plutil -extract "$pose.$facing.fps" raw -o - "$HERE/animations.json")

  {
    echo
    echo "/* $pose, facing $facing: $frames frame(s) of ${cell}x${height} at ${fps}fps"
    echo "   (source art $((cell / HERO_SCALE))x$((height / HERO_SCALE)), rendered at --scale $HERO_SCALE) */"
    echo ".jumbini-$pose {"
    echo "  width: ${cell}px;"
    echo "  height: ${height}px;"
    echo "  background-image: url(\"$file\");"
    echo "  background-size: $((cell * frames))px ${height}px;"
    echo "  background-repeat: no-repeat;"
    echo "  image-rendering: pixelated;"
    if [ "$frames" -gt 1 ]; then
      # steps(N) with a background-position that travels the full sheet width:
      # the last step lands one cell past the last frame, which is where the
      # loop restarts. Duration is frames/fps, so the loop runs at the rate the
      # app plays it.
      echo "  animation: jumbini-$pose $(awk -v f="$frames" -v r="$fps" 'BEGIN { printf "%.3f", f / r }')s steps($frames) infinite;"
      echo "}"
      echo "@keyframes jumbini-$pose {"
      echo "  from { background-position: 0 0; }"
      echo "  to   { background-position: -$((cell * frames))px 0; }"
      echo "}"
    else
      echo "  /* single frame in the app's table — nothing to animate. */"
      echo "}"
    fi
  } >>"$css"
}

hero_sheet walk east
hero_sheet run east
hero_sheet idle south
hero_sheet sit south
echo "hero: sheets and $css written to $HERO"
echo

# ---------------------------------------------------------------------------
# Stills

echo "stills: hero"
"${FILM[@]}" still --pose idle --facing south --scale 6 --out "$OUT/hero@2x.png"

echo "stills: rotations contact sheet"
"${FILM[@]}" contact --pose idle --scale 3 --out "$OUT/rotations.png"

echo "stills: coats, side by side"
"${FILM[@]}" pair --pose idle --facing south --coat classic --coat2 shaggy \
  --scale 5 --out "$OUT/coats.png"

echo
echo "stills: the remaining three are screenshots of live UI and cannot be rendered."
echo "stills: with Jumbini running:"
echo "stills:   1. wardrobe.png  — open the Wardrobe menu, then: screencapture -iw \"$OUT/wardrobe.png\""
echo "stills:   2. menubar.png   — open the menu bar menu, then: screencapture -iw \"$OUT/menubar.png\""
echo "stills:   3. jumbini-cam.png — press ⌥⇧J, then paste the clipboard into Preview and save"
echo "stills: done. Offline stills are in $OUT"
